name: tests

on:
  push:
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: v0.11.2
          neovim: true
      - name: Run regression tests
        run: nvim --headless -u NONE -l tests/run.lua
